import "../(user)/globals.css"
import { Inter } from 'next/font/google'
import Header from "@/app/components/Header"
import Footer from "@/app/components/Footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blogs',
  description: 'Generated by create next app',
}

export const revalidate = 10;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col justify-between bg-slate-900">
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  )
}